"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Products", [
      {
        AuthorId: 1,
        CategoryId: 1,
        categoryName: "Rice",
        sku: "MHW23Q",
        name: "BEN'S ORIGINAL™ READY RICE™ Jasmine Rice",
        description:
          "Savor the delicious taste of traditional Thai Jasmine rice and satisfy your desire for Southeast Asian cuisine in just 90 seconds with BEN'S ORIGINAL™ READY RICE™ Jasmine Rice.",
        weight: 240,
        image:
          "https://www.bensoriginal.com/cdn-cgi/image/width=600,height=600,f=auto,quality=90/sites/g/files/fnmzdf306/files/migrate-product-files/elc9tlj4wgj7tcgbqk66.png",
        price: 500000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 1,
        categoryName: "Flour",
        sku: "NAQ55A",
        name: "Golden Eagle Donut Mix",
        description:
          "Specially formulated so that it can be processed easier and faster, the Golden Eagle Donut Mix will ensure the results of a fluffy and perfect fluffy donut.",
        weight: 1000,
        image:
          "https://bungasari.com/assets/img/1624973848_2021-packaging-premix-10kg-_-1kg-donut.png",
        price: 250000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 1,
        categoryName: "Sugar",
        sku: "ZAW12B",
        name: "N'Joy Sugar Canister",
        description:
          "ALL THE SWEET, NONE OF THE CHEMICALS: N'Joy 100% pure sugar packaged in an easy-to-pour Canister. Bulk size includes six 20-oz. Sugar Canisters",
        weight: 120,
        image:
          "https://m.media-amazon.com/images/I/51yc45Yf2iL._SX679_PIbundle-6,TopRight,0,0_AA679SH20_.jpg",
        price: 150000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 1,
        categoryName: "Cooking Oil",
        sku: "BWO45M",
        name: "Crisco Pure Vegetable Oil, 64 Fluid Ounce",
        description:
          "Made from soybeans, with a light taste that lets the flavor of your food shine through",
        weight: 1000,
        image: "https://m.media-amazon.com/images/I/51Eg8k9hyuL._SY679_.jpg",
        price: 450000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 1,
        categoryName: "Salt",
        sku: "QOT24A",
        name: "Hain Pure Foods Iodized Sea Salt",
        description: "One 21 oz. Canister of Hain Pure foods Iodized sea salt",
        weight: 600,
        image: "https://m.media-amazon.com/images/I/61EK5fHr9gL._SX679_.jpg",
        price: 245000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 2,
        categoryName: "Tea",
        sku: "TBM40A",
        name: "Lipton Black Tea Bags for Hot or Iced Tea",
        description:
          "What You'll Get - Healthy heart Lipton Black Tea with caffeine, orange pekoe and pekoe cut black tea leaves for a smooth taste, 100 tea bags per pack, 6 packs total",
        weight: 240,
        image:
          "https://m.media-amazon.com/images/I/810bHm7JnnL._SX679_PIbundle-6,TopRight,0,0_AA679SH20_.jpg",
        price: 450000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 2,
        categoryName: "Coffee",
        sku: "CQO25P",
        name: "Lavazza Espresso Whole Bean Coffee Blend",
        description:
          "Best used for espresso but also suitable in any coffee maker. Blend: 100% arabica",
        weight: 2200,
        image: "https://m.media-amazon.com/images/I/61XoFICFZtL._SL1500_.jpg",
        price: 350000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 2,
        categoryName: "Bottled Water",
        sku: "BWA10M",
        name: "Pure Life, Purified Water",
        description:
          "A Taste You Can Trust: From collection to testing, our quality process ensures you and your family are getting the quality you deserve",
        weight: 2900,
        image: "https://m.media-amazon.com/images/I/712nRlopEAL._SX679_.jpg",
        price: 600000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 2,
        categoryName: "Soft Drinks",
        sku: "SQP35A",
        name: "Dr Pepper Strawberries and Cream Soda",
        description:
          "ORIGINAL FLAVOR: Dr Pepper continues to innovate with new and exciting flavors like Dr Pepper Strawberries & Cream.",
        weight: 350,
        image: "https://m.media-amazon.com/images/I/81yQGVjk7UL._SL1500_.jpg",
        price: 80000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 2,
        categoryName: "Juice",
        sku: "JAO20Q",
        name: "Ocean Spray® Pink Cranberry Juice Cocktail",
        description:
          "Endless Possibilities - Serve with vodka or champagne for festive beverages, enjoy chilled on its own or add to gelatin for a tasty dessert",
        weight: 1800,
        image: "https://m.media-amazon.com/images/I/71fiv6JyqwL._SL1500_.jpg",
        price: 400000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 3,
        categoryName: "Biscuits",
        sku: "BAP50A",
        name: "Nutella Biscuits, Hazelnut Spread With Cocoa",
        description:
          "TIMELESS NUTELLA: Beloved worldwide, Nutella is famous for its authentic hazelnut and cocoa taste, made even more irresistible by its unique creaminess.",
        weight: 275,
        image: "https://m.media-amazon.com/images/I/81ZKoxVXXtL._SL1500_.jpg",
        price: 150000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 3,
        categoryName: "Chips",
        sku: "CQP56A",
        name: "Kirkland Signature Himalayan Salt Potato Chips",
        description:
          "Fresh potatoes cut thick and fried to our signature crunch, then seasoned with Himalayan salt to bring out the flavor of the potatoes",
        weight: 900,
        image: "https://m.media-amazon.com/images/I/81mVrdioyFL._SY679_.jpg",
        price: 250000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 3,
        categoryName: "Candy",
        sku: "CPO45Q",
        name: "Laffy Taffy Candy, Fruit Combos, Individually Wrapped Mini Bars",
        description:
          "MINI BARS, MAX FLAVOR: Each mini bar offers a world of taffy flavor & fun! Individually packaged for a quick pick-me-up and giggle, Laffy Taffy brings smiles out of hiding with its tasty wrapped laughs.",
        weight: 170,
        image: "https://m.media-amazon.com/images/I/61otTXYCDbL._SL1000_.jpg",
        price: 200000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 3,
        categoryName: "Chocolate",
        sku: "CPL54A",
        name: "HERSHEY'S NUGGETS Assorted Chocolate",
        description:
          "Use HERSHEY'S candy for filling birthday gift bags and back-to-school lunch boxes or bridal and baby shower candy dishes",
        weight: 895,
        image: "https://m.media-amazon.com/images/I/71OPlMw2bcL._SL1500_.jpg",
        price: 300000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 3,
        categoryName: "Nuts",
        sku: "NMA90A",
        name: "Mariani Nut - Shelled Premium California Walnuts",
        description:
          "PREMIUM: Each naturally heart-healthy walnut is freshly harvested from California farms to provide the perfect crunch",
        weight: 920,
        image: "https://m.media-amazon.com/images/I/71s-to-+VPL._SX679_.jpg",
        price: 225000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 4,
        categoryName: "Canned Vegetables",
        sku: "CQP50M",
        name: "Del Monte Canned Fresh Cut Golden Sweet Whole Kernel Corn No Salt Added",
        description:
          "Picked and packed at the peak of freshness. Rich, sweet flavor.",
        weight: 250,
        image:
          "https://www.delmonte.com/sites/default/files/Whole%20Kernel%20Corn_1050x500.png",
        price: 325000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 4,
        categoryName: "Canned Fruits",
        sku: "FPQ30Q",
        name: "365 by Whole Foods Market, Organic Yellow Cling Peach Slices",
        description:
          "Trust & Quality We Are Proud To Offer This Product To You Because It Meets Our Rigorous Quality Standards, Which Prohibit Over 100 Ingredients For Both Food And Supplements.",
        weight: 425,
        image: "https://m.media-amazon.com/images/I/51cVZdsgI2L._SL1000_.jpg",
        price: 75000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 4,
        categoryName: "Canned Fish",
        sku: "FZP45M",
        name: "Beach Cliff Wild Caught Sardines in Mustard Sauce",
        description:
          "WILD CAUGHT SARDINES IN MUSTARD SAUCE: Premium, high-quality wild caught canned sardines in mustard sauce will satisfy you when you want a tasty and healthy snack, lunch or dinner",
        weight: 110,
        image: "https://m.media-amazon.com/images/I/81WlaAiByGL._SX679_.jpg",
        price: 300000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 4,
        categoryName: "Canned Meat",
        sku: "MAZ50A",
        name: "Mary Kitchen Hash Corned Beef Hash",
        description:
          "Made from a mix of tender corned beef chunks, diced potatoes, and savory seasonings, you can bring that classic restaurant taste of corned beef hash to your home",
        weight: 400,
        image: "https://m.media-amazon.com/images/I/718Njaz7RQL._SL1500_.jpg",
        price: 525000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 4,
        categoryName: "Soups",
        sku: "SPZ67A",
        name: "Campbells Chunky Soup",
        description:
          "Pantry Staple: Enjoy this soup at home or at work as part of a delicious, filling lunch, or take on outdoor adventures to eat by the campfire",
        weight: 535,
        image: "https://m.media-amazon.com/images/I/81YNxrZnsnL._SX679_.jpg",
        price: 330000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 5,
        categoryName: "Black Cumin",
        sku: "CPA90M",
        name: "Life Extension Black Cumin Seed Oil",
        description:
          "Black cumin is one of the most ancient beneficial herbs. Although it has been used as a spice, dont confuse it with cumin.",
        weight: 50,
        image: "https://m.media-amazon.com/images/I/71uhArjDGqL._AC_SY879_.jpg",
        price: 225000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 5,
        categoryName: "Pepper",
        sku: "PLK60A",
        name: "Olde Thompson Fine Black Pepper",
        description:
          "Professional chef quality: Ideal for use in commercial restaurant kitchens or at home for your personal culinary endeavors.",
        weight: 2300,
        image: "https://m.media-amazon.com/images/I/8131hixaRZS._SL1500_.jpg",
        price: 450000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 5,
        categoryName: "Chili Powder",
        sku: "CPL24M",
        name: "McCormick Dark Chili Powder",
        description:
          "McCormick Dark Chili Powder always starts with whole, ripe peppers. A robust blend of ripe peppers, garlic, salt and spices.",
        weight: 570,
        image: "https://m.media-amazon.com/images/I/81eVnw1athL._SL1500_.jpg",
        price: 210000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 5,
        categoryName: "Turmeric",
        sku: "TPZ20A",
        name: "Me First Living Turmeric Curcumin",
        description:
          "Highest potency available; Our premium turmeric curcumin supplement contains 1000mg of standardized turmeric extract 95% curcuminoids per serving.",
        weight: 900,
        image: "https://m.media-amazon.com/images/I/71eZYecAGxL._AC_SY879_.jpg",
        price: 445000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 5,
        categoryName: "Cinnamon",
        sku: "CPA21M",
        name: "McCormick Ground Cinnamon",
        description:
          "Deep, sweet, warm flavor and rich mahogany color. Premium quality for pure, superior flavor; never made with added fillers.",
        weight: 200,
        image: "https://m.media-amazon.com/images/I/81LJnXAvjjL._SX679_.jpg",
        price: 95000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 6,
        categoryName: "Laundry Detergent",
        sku: "LZM50A",
        name: "Dropps Stain & Odor Laundry Detergent Pods",
        description:
          "Experience a new level of clean with Dropps Stain & Odor Laundry Detergent Pods, designed to tackle even the most stubborn stains and persistent odors.",
        weight: 800,
        image:
          "https://m.media-amazon.com/images/I/71SacNKLNwL._AC_SL1500_.jpg",
        price: 320000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 6,
        categoryName: "Dish Soap",
        sku: "DPM50A",
        name: "Cleancult Dish Soap Liquid Refills",
        description:
          "Clean isnt just a state, its a feeling we facilitate. Our dishwashing liquid converts dirty dishes into sparkling clean ones.",
        weight: 1000,
        image: "https://m.media-amazon.com/images/I/71qHig87-jL._AC_SX679_.jpg",
        price: 425000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 6,
        categoryName: "All purpose cleaner",
        sku: "PZM40C",
        name: "Cleancult - Wild Lavender - All Purpose Cleaner",
        description:
          "Our all purpose cleaner spray is made from safe biodegradable ingredients, and our clear liquid formulas are free from harsh chemicals while being gentle on your home and the planet.",
        weight: 500,
        image: "https://m.media-amazon.com/images/I/5121hZgPAEL._AC_SX679_.jpg",
        price: 75000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 6,
        categoryName: "Brooms",
        sku: "BZP20A",
        name: "O-Cedar PowerCorner One Sweep Broom with Step-On Dustpan and 3-Piece Handle, Red",
        description:
          "Features angled firm black bristles that thoroughly pull dirt from corners; and semi-soft grey bristles that capture and move dirt effectively",
        weight: 900,
        image:
          "https://m.media-amazon.com/images/I/71Jzw4oNJcL._AC_SL1500_.jpg",
        price: 225000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 6,
        categoryName: "Mops",
        sku: "MZP25A",
        name: "O-Cedar Microfiber Cloth Wet Mop,Blue/Red",
        description:
          "O-Cedar's best selling commercial mop. Is eco-friendly and machine washable up to 100x",
        weight: 1250,
        image:
          "https://m.media-amazon.com/images/I/71JtR5xw44L._AC_SL1500_.jpg",
        price: 200000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 7,
        categoryName: "Soap",
        sku: "SZP01A",
        name: "Dove Beauty Bar Gentle Skin Cleanser Shea Butter",
        description:
          "Dove Shea Butter Beauty Bar is a moisturizing, gentle cleanser that has the warm, comforting scents of shea butter and vanilla",
        weight: 115,
        image: "https://m.media-amazon.com/images/I/71b6yPN6jKL._SX466_.jpg",
        price: 185000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 7,
        categoryName: "Shampoo",
        sku: "SLM10A",
        name: "Herbal Essences Sulfate Free Shampoo with Honey for Daily Moisture",
        description:
          "Herbal Essences Sulfate Free Shampoo with Honey for Daily Moisture, Nourishes Dry Hair, Moisturizing Shampoo with Certified Camellia Oil and Aloe Vera, Lightweight For All Hair.",
        weight: 1000,
        image: "https://m.media-amazon.com/images/I/71EJZsekXOL._SL1500_.jpg",
        price: 330000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 7,
        categoryName: "Toothpaste",
        sku: "TPM10A",
        name: "Davids Fluoride Free Nano Hydroxyapatite Toothpaste for Remineralizing Enamel & Sensitive Relief",
        description:
          "Features Nano Hydroxyapatite (n-HA) - the same ingredient that naturally makes up 97% of your teeth material.",
        weight: 150,
        image:
          "https://m.media-amazon.com/images/I/61F7JjVYxLL._AC_SL1351_.jpg",
        price: 160000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 7,
        categoryName: "Toilet Paper",
        sku: "TPZ09M",
        name: "Quilted Northern Ultra Plush Toilet Paper",
        description:
          "Quilted Northern Ultra Plush toilet paper is designed for optimal softness and premium performance, while cutting down on what you dont want lint",
        weight: 750,
        image:
          "https://m.media-amazon.com/images/I/81EYJsPHH1L._AC_SL1500_.jpg",
        price: 425000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 7,
        categoryName: "Sanitary Napkins",
        sku: "SMZ01M",
        name: "Hyye Daily Slim Sanitary Pads with Wings for Women",
        description:
          "Soft-touch cover suitable for sensitive skin without causing itching and fluffiness. Ultra absorbency, thin structure for daytime activities.",
        weight: 350,
        image: "https://m.media-amazon.com/images/I/410hGsHJnML._AC_SX679_.jpg",
        price: 90000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 8,
        categoryName: "Frozen Vegetables",
        sku: "FZM20A",
        name: "Birds Eye Steamfresh Broccoli Florets",
        description:
          "Frozen broccoli florets are a quick, easy side dish option. Flash frozen broccoli locks in fresh flavor",
        weight: 310,
        image: "https://m.media-amazon.com/images/I/816o3YwmT6L._SL1500_.jpg",
        price: 200000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 8,
        categoryName: "Frozen Fruits",
        sku: "FFZ20A",
        name: "Deebee's 100% Organics Super Fruit Freezie Frozen Juice Bars",
        description:
          "Nut, Gluten and Dairy-Free: A smart choice for classrooms and daycares, these frozen popsicles are free of the top 8 allergens!",
        weight: 400,
        image:
          "https://m.media-amazon.com/images/I/91R+mPtuD8L._SY679_PIbundle-30,TopRight,0,0_SX487SY679SH20_.jpg",
        price: 320000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 8,
        categoryName: "Frozen Meals",
        sku: "FMM20A",
        name: "Banquet Chicken Nuggets with Mac and Cheese and Brownie, Frozen Meal",
        description:
          "Even when you don't have time to cook, Banquet meals ensure you can still have a hot and satisfying meal for lunch or dinner anytime, right out of the microwave",
        weight: 210,
        image: "https://m.media-amazon.com/images/I/810BlPhCRwL._SX679_.jpg",
        price: 250000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 8,
        categoryName: "Ice Cream",
        sku: "ICM10Z",
        name: "Junket Ice Cream Mix Simply Strawberry",
        description:
          "Simple to make: Custom, homemade ice cream is easy to make with Junket Ice Cream Mix. Just add milk and cream for one quart of satisfyingly smooth, flavorful ice cream the whole family will enjoy!",
        weight: 160,
        image: "https://m.media-amazon.com/images/I/71-0As5ztjL._SL1500_.jpg",
        price: 525000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 8,
        categoryName: "Frozen Fish",
        sku: "FFZ09Q",
        name: "Gorton's, Crunchy Breaded Fish Sticks",
        description:
          "Crunchy breaded fish sticks with simple, flavorful ingredients, Great for kids! 100% real fish, no fillers.",
        weight: 700,
        image: "https://m.media-amazon.com/images/I/810SPCdrmyL._SL1500_.jpg",
        price: 400000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 9,
        categoryName: "Milk",
        sku: "MMO01P",
        name: "Horizon Organic 2% Reduced Fat Milk, High Vitamin D, Half Gallon",
        description:
          "DELICIOUS AND NUTRITIOUS: Reduced fat organic milk with a rich, creamy taste thats sure to please the family. ORGANIC GOODNESS: Certified USDA Organic milk from happy cows raised by our trusted farmer partners.",
        weight: 1900,
        image: "https://m.media-amazon.com/images/I/71ynaTPufaL._SL1500_.jpg",
        price: 75000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 9,
        categoryName: "Cheese",
        sku: "CPZ20M",
        name: "Kerrygold Dubliner Parchment, Packaged-cheddar-cheeses",
        description:
          "With complex flavors that are easy to enjoy, Dubliner is our best selling cheese for a reason. This aged Irish cheese is made on family farms from the milk of grass-fed cows that graze on lush Irish pastures.",
        weight: 200,
        image: "https://m.media-amazon.com/images/I/51JlpOFWWJL._SX679_.jpg",
        price: 125000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 9,
        categoryName: "Yogurt",
        sku: "YZP20M",
        name: "siggi's Icelandic Strained Nonfat Yogurt",
        description:
          "siggi's Icelandic Strained Nonfat Peach Yogurt has more protein than sugar making for a quick breakfast, nutritious snack, or afternoon pick-me-up.",
        weight: 150,
        image: "https://m.media-amazon.com/images/I/81du4DBF0LL._SL1500_.jpg",
        price: 750000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 9,
        categoryName: "Eggs",
        sku: "EZP20A",
        name: "Pecking order Ceramic Nest Eggs",
        description:
          "Use for Nest Box Training to Teach Hens Which Nest Box to Lay In & Prevent Hens Laying on Coop Floors",
        weight: 300,
        image:
          "https://m.media-amazon.com/images/I/81giHdc4veL._AC_SL1500_.jpg",
        price: 150000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 9,
        categoryName: "Butter",
        sku: "BMZ10A",
        name: "President, Imported Butter Salted",
        description:
          "High quality imported salted butter. From pasteurized cows milk. Product of France",
        weight: 200,
        image: "https://m.media-amazon.com/images/I/41bCFFwFwgL.jpg",
        price: 150000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 10,
        categoryName: "Light Bulbs",
        sku: "LBZ20M",
        name: "SYLVANIA ECO LED Light Bulb",
        description:
          "A19 60W Equivalent, Efficient 9W, 7 Year, 750 Lumens, 2700K, Non-Dimmable, Frosted, Soft White - 8 Count (Pack of 1) (40821)",
        weight: 750,
        image: "https://m.media-amazon.com/images/I/81wKhRO66oL._AC_SX679_.jpg",
        price: 190000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 10,
        categoryName: "Batteries",
        sku: "BMP20A",
        name: "Duracell Coppertop AAA Batteries with Power Boost Ingredients",
        description:
          "Duracell Coppertop AAA alkaline batteries contain Duracells patented POWER BOOST Ingredients which deliver lasting performance in your devices.",
        weight: 500,
        image: "https://m.media-amazon.com/images/I/71X+QeAikhL._AC_SX679_.jpg",
        price: 300000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 10,
        categoryName: "Stationery",
        sku: "SPM25A",
        name: "iBayam Journal Planner Pens Colored Pens Fine Point Markers Fine Tip Drawing Pens",
        description:
          "Smart Fineliner Color Pens Set 18 Unique Colors, 0.38 mm Fine Point Colored Pens, With water-based ink, Minimal Bleed Thru Ink, Assorted Color Fine Tip Marker Pens.",
        weight: 900,
        image: "https://m.media-amazon.com/images/I/61zwYT19njL._AC_SX466_.jpg",
        price: 125000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 10,
        categoryName: "Matches",
        sku: "MPQ59B",
        name: "Diamond Kitchen Matches",
        description: "Diamond Kitchen Matches, 2/250ct",
        weight: 100,
        image: "https://m.media-amazon.com/images/I/51flsOwoB3L._AC_SX679_.jpg",
        price: 75000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        AuthorId: 1,
        CategoryId: 10,
        categoryName: "Trash Bags",
        sku: "TBP09M",
        name: "Genuine Joe 01534 Heavy-Duty Trash Bags",
        description:
          "Genuine Joe 01534 Heavy-Duty Trash Bags, 1.5 Mil, 40-45 Gallon, 50/CT, Black",
        weight: 250,
        image: "https://m.media-amazon.com/images/I/617dJ04o12L._SL1500_.jpg",
        price: 350000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Products", null, {});
  },
};
